# Generated by Django 3.2.13 on 2022-11-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade_avg',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
