# Generated by Django 3.2.13 on 2022-11-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_grade_avg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='grade_1',
            new_name='grade_design',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='grade_2',
            new_name='grade_durability',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='grade_3',
            new_name='grade_practicality',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='grade_4',
            new_name='grade_price',
        ),
    ]
